name: Pull from code.maralorn.de
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull main if fast-forward
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Current commit: $(git rev-parse HEAD)"

          # Add remote if it doesn't exist
          if ! git remote get-url forgejo >/dev/null 2>&1; then
            git remote add forgejo \
              https://code.maralorn.de/maralorn/nix-output-monitor.git
          fi

          # Fetch latest changes from forgejo
          git fetch forgejo main

          # Check if fast-forward is possible
          if git merge-base --is-ancestor HEAD forgejo/main; then
            echo "Fast-forward merge possible"
            git merge --ff-only forgejo/main
            git push origin main
            echo "Successfully updated main branch"
          else
            echo "Fast-forward not possible - manual intervention required"
            exit 1
          fi
