name: Nix build
on:
  pull_request:
  push:
    branches: [main]

run-name: Test and build flake
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: cachix/install-nix-action@v31
      - run: nix flake check
      - run: nix build
